### PR TITLE
Removed .truncate-multiline rule which used deprecated flexbox in WebKit/Blink from news sites.

### PR DESCRIPTION
**Pull request by rniwa**
Fixes the issue #318.

### CODE REVIEW

**Comment by rniwa** [comment]
No substantive change to the scores before/after the change:

Chrome
Before: 13.4 ± 0.19
After: 13.4 ± 0.49

Firefox
Before: 12.4 ± 0.41
After: 12.6 ± 0.47

Safari
Before: 10.5 ± 0.38
After: 10.4 ± 0.28

[remove-truncate-multiline-rule.zip](https://github.com/WebKit/Speedometer/files/12786771/remove-truncate-multiline-rule.zip)

**Comment by flashdesignory** [comment]
the css classes do have a purpose of truncating text that's too long. 
Simply removing the rule makes the concern mention in the issue go away, but alters the workload. 

What's a cross browser css rule to truncate text (one line and multi-line) from your perspective?

**Comment by rniwa** [comment]
Probably https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by flashdesignory** [comment]
> Probably https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

that works for a single line, but not for multi-line... it's used in "truncate-singleline" already.

**Comment by flashdesignory** [comment]
Just to make sure - I am totally fine with replacing the css rule with a more appropriate rule for multi-line truncation. 
I was not able to find a CSS solution that results in the same display as the one in question here.

**Comment by rniwa** [comment]
Yeah, I don't think there is a cross-browser way to do it, in which case, we should just get rid of the rule.

**Comment by flashdesignory** [comment]
Curious what other folks think... 
I definitely don't want to remove the CSS rules, since that changes how the site behaves. 

A minimum would be something like below at least. 
We'd loose the elipsis, but at least the height of the elements stays consistent. 

```
.truncate-multiline {
    max-height: calc(2 * var(--font-size-xlarge));
    display: flex;
    overflow: hidden;
}

.truncate-multiline-3 {
    max-height: calc(3 * var(--font-size-xlarge));
}
```

**Comment by rniwa** [comment]
> > Yeah, I don't think there is a cross-browser way to do it, in which case, we should just get rid of the rule.
> 
> I commented in [#318 (comment)](https://github.com/WebKit/Speedometer/issues/318#issuecomment-1745754725) as well, but this has been supported in Firefox for ~5 years https://bugzilla.mozilla.org/show_bug.cgi?id=WebKit-line-clamp

Oh, interesting. I wasn't aware of that. I guess we can keep it in this case.

**Pull request closed without merging**
