### PR TITLE
Add Speedometer Governance Policy

### PR DESCRIPTION
**Pull request by rniwa**

### CODE REVIEW

**Review by addyosmani — APPROVED** [review]
LGTM as discussed.

**Comment by bgrins** [comment]
Text looks good to me. Could we put this in a separate file (something like policy.md or governance.md)? That way we could keep the readme more focused on an introduction (what the project is, goals, etc) and link to this doc from there.

**Comment by rniwa** [comment]
> Text looks good to me. Could we put this in a separate file (something like policy.md or governance.md)? That way we could keep the readme more focused on an introduction (what the project is, goals, etc) and link to this doc from there.

Since the first sentence reads "[i]n order to achieve the goals above," it seems that we want the goal & governance in th same document?

**Review by bgrins — APPROVED** [review]
Thanks!

**Comment by rniwa** [comment]
@addyosmani : does this still look good to you after moving it to governance.md?

**Comment by addyosmani** [comment]
> @addyosmani : does this still look good to you after moving it to governance.md?

It does indeed. LGTM.

**Pull request merged**
