### PR TITLE
Enable complex DOM benchmarks execution in official speedometer run

### PR DESCRIPTION
**Pull request by issackjohn**
### Selected TodoMVC tests for complex setting
- Angular
- JavaScript-ES6-Webpack
- Lit
- Preact
- React
- Svelte

### Selected TodoMVC tests for the stand-alone setting
- WebComponents
- JavaScript-ES5
- React-Redux
- Backbone
- Vue
- jQuery

### Hosted version: https://issackjohn.github.io/SpeedometerWithComplex/#home

### CODE REVIEW

**Comment by issackjohn** [comment]
Added major change label: https://github.com/WebKit/Speedometer/pull/264#issuecomment-1615149544

**Comment by rniwa** [comment]
Could you squash all the commits?

**Comment by issackjohn** [comment]
> Could you rebase and squash all the commits?

Done

**Comment by rniwa** [comment]
Thanks. We'd like to see https://github.com/WebKit/Speedometer/issues/335 resolved before merging this PR.

**Comment by bgrins** [comment]
Here's a commit that switches to the new list of tests https://github.com/mozilla/Speedometer/commit/bb19795ad265bfe27ec25eb66c88e6bf50c60541

**Comment by issackjohn** [comment]
> Here's a commit that switches to the new list of tests [mozilla@bb19795](https://github.com/mozilla/Speedometer/commit/bb19795ad265bfe27ec25eb66c88e6bf50c60541)

Thank you, I plan to make the same change.

**Comment by issackjohn** [comment]
> Here's a commit that switches to the new list of tests [mozilla@bb19795](https://github.com/mozilla/Speedometer/commit/bb19795ad265bfe27ec25eb66c88e6bf50c60541)

I did notice that TodoMVC-React was not disabled in the commit you linked, and I have disabled it in this PR as every TodoMVC test would execute either in the complex or stand-alone setting.

**Review by bgrins — APPROVED** [review]
Thanks. Matches the test set we decided on, and should be landable alongside the upcoming isolation variant

**Review by flashdesignory — APPROVED** [review]

**Review by rniwa — APPROVED** [review]

**Comment by sulekhark** [comment]
Thank you all for your support with the Complex DOM workload!

**Pull request merged**
