### PR TITLE
TodoMVC web component: change css rule, run build on complex

### PR DESCRIPTION
**Pull request by flashdesignory**
using `word-wrap: break-word` for consistency. The web component version actually also uses truncation, so it doesn't have any visual effect. Reason why I think it's still relevant is that we have an open issue in the official css package as well: https://github.com/tastejs/todomvc-app-css/issues/40

additionally, I don't know why the complex version has more changes after running the build script. 
Maybe another pr merged an older version "over" my previous changes? 🤷 .

@kara

### CODE REVIEW

**Comment by lpardosixtosMs** [comment]
Thanks for rebuilding the complex version, looks like it wasn't updated in #314.

**Review by julienw — APPROVED** [review]
thanks

**Comment by rniwa** [comment]
Do we have before/after numbers?

**Comment by flashdesignory** [comment]
chrome before:
chrome_before

chrome after:
chrome_after

firefox before:
firefox_before

firefox after:
firefox_after

safari before:
safari_before

safari after:
safari_after

edge before:
edge_before

edge after:
edge_after

**Comment by rniwa** [comment]
Thanks

**Review by rniwa — APPROVED** [review]

**Pull request merged**
