### PR TITLE
Small lint-related fixes

### PR DESCRIPTION
**Pull request by julienw**
Here are a few fixes for small problems I found while working on the project lately.
Commits should be fairly independent so feel free to look at them separately.

1. Remove tentative/ from the ignore lists. Indeed there's no tentative workload anymore, but working on some on local branches I find it easier that prettier and eslint are not disabled on these directories.
2. This makes tsx files checked by the eslint, as well as mirror the check with the fix configuration.
3. It's good practice to put `root: true` on the top level eslint configuration file. Reference: https://eslint.org/docs/latest/use/configure/configuration-files#cascading-and-hierarchy
4. While running eslint, I found this false positive about the next eslint plugin. It was due to a misconfiguration in the newssite-next directory, so I fixed this in the process.
5. Some file wasn't properly formatted.

### CODE REVIEW

**Review by flashdesignory — APPROVED** [review]
Thanks for the cleanup!

**Comment by julienw** [comment]
I believe just one r+ is enough for this, right?

**Review by rniwa — APPROVED** [review]

**Comment by rniwa** [comment]
> I believe just one r+ is enough for this, right?

In theory, yes.

**Comment by julienw** [comment]
2 r+ is more than enough then :) thanks for the reviews

**Pull request merged**
