### PR TITLE
Make the number of airports per group configurable and use it in tests

### PR DESCRIPTION
**Pull request by julienw**
This is a follow-up to #144.

In Firefox I see more work related to styling in the async marker when configured to "20".
What do you think @rniwa?

### CODE REVIEW

**Review by rniwa — APPROVED** [review]
Seems reasonable.

**Comment by julienw** [comment]
what do you think @flashdesignory ?

**Review by flashdesignory — APPROVED** [review]
LGTM

**Comment by julienw** [comment]
Thanks! Now I just need somebody to merge :-)

**Pull request merged**
