### PR TITLE
Remove extra todo-list element in javascript-web-components

### PR DESCRIPTION
**Pull request by issackjohn**
Before:
image
After:
image

### CODE REVIEW

**Review by flashdesignory — APPROVED** [review]

**Comment by rniwa** [comment]
Can we get before/after numbers?

**Comment by flashdesignory** [comment]
> Can we get before/after numbers?

@issackjohn - you can screenshot the details page for that workload, by bringing up our dev tools and selecting just that one workload:

http://127.0.0.1:7000/?developerMode

**Comment by issackjohn** [comment]
I don't have machine to get safari numbers with.
Chrome before:
image
Chrome after:
image
Firefox before:
image
Firefox after:
image

**Comment by flashdesignory** [comment]
I'll go ahead and merge

**Pull request merged**
