### PR TITLE
TodoMVC - React - add id to input

### PR DESCRIPTION
**Pull request by flashdesignory**
This adds an id to the toggle all input - see: https://github.com/tastejs/todomvc/pull/2257

@kara

### CODE REVIEW

**Review by julienw — COMMENTED** [review]
looks good to me, but:
* the same issue exists in the workload for react-redux and preact, can you please fix them as well?
* the "complex" versions of these workloads need to be rebuilt as well

Thanks!

**Comment by flashdesignory** [comment]
> looks good to me, but:
> 
>     * the same issue exists in the workload for react-redux and preact, can you please fix them as well?
> 
>     * the "complex" versions of these workloads need to be rebuilt as well
> 
> 
> Thanks!

Oh thanks for taking a look at the other ones. 
I'll fix those too and rebuild the complex versions

**Review by julienw — APPROVED** [review]
thanks!

**Comment by flashdesignory** [comment]
@rniwa - any concerns to merge this?

**Review by rniwa — APPROVED** [review]
seems ok.

**Pull request merged**
