### PR TITLE
[Editors] Group the Create step into the next step

### PR DESCRIPTION
**Pull request by julienw**
This is a tentative to reduce the variance in Chrome. There's still a variance for the first run especially, but the create step doesn't contribute to it anymore. It was a quite short step so I believe it makes sense. 
I moved the create step in the "long" step. I had to refactor a few things in the workloads because of this.

[main branch](https://speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap)
[main branch with raf](https://speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap&measurementMethod=raf)
[this patch's preview](https://group-more-editor-steps--speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap)
[this patch's preview with raf](https://group-more-editor-steps--speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap&measurementMethod=raf)

Tell me what you all think!

### CODE REVIEW

**Comment by rniwa** [comment]
Hm... I'm still seeing 20% variance on Chrome:

Editor-CodeMirror	27.99	±	6.20 (22.1%)	ms
Editor-TipTap	98.53	±	6.78 (6.9%)	



Iteration | Editor-CodeMirror [ms] | Editor-TipTap [ms]
-- | -- | --
0 | 51.40 | 122.90
1 | 24.10 | 97.40
2 | 25.60 | 104.80
3 | 29.60 | 97.00
4 | 25.10 | 97.00
5 | 27.90 | 90.10
6 | 23.40 | 92.70
7 | 23.30 | 95.30
8 | 20.80 | 91.50
9 | 28.70 | 96.60

**Comment by julienw** [comment]
Yes, I wrote exactly this in the description :-) I don't think we can fix it, I believe this is chrome caching things.

**Comment by camillobruni** [comment]
I think the main overhead in chrome is the initial compilation here:

Editor-CodeMirror/Long
Iteration 0:
Screenshot 2023-06-08 at 23 52 59

Iteration 1:
Screenshot 2023-06-08 at 23 53 59

Iteration 2:
Screenshot 2023-06-08 at 23 54 39

**Comment by bgrins** [comment]
Based on the discussion in #214 I sense this shouldn't block getting these out of tentative. We can spend some more time to investigate whether we can/should mitigate some of the caching effects but it seems like this change alone isn't going to fundamentally change what's happening.

**Comment by camillobruni** [comment]
I do like he larger individual step durations.
I do occasionally get sporadically a random long step in there though, so far no luck properly reproing.

**Review by camillobruni — APPROVED** [review]

**Review by rniwa — APPROVED** [review]

**Review by bgrins — APPROVED** [review]

**Pull request merged**
