### PR TITLE
Todomvc styles - consistent versions

### PR DESCRIPTION
**Pull request by flashdesignory**
Clean-up pr to ensure all upgraded todomvc apps are using the same version of the todomvc styles:

```
"todomvc-app-css": "^2.4.2",
 "todomvc-common": "^1.0.5"
```

@kara

### CODE REVIEW

**Review by bgrins — APPROVED** [review]
Makes sense. I haven't run this locally to confirm styles all look right in the affected tests but these look like straightforward updates to me

**Comment by rniwa** [comment]
We need before/after numbers.

**Comment by flashdesignory** [comment]
> We need before/after numbers.

sounds like a plan - I'll add them!

**Comment by flashdesignory** [comment]
scores:
backbone: https://gist.github.com/flashdesignory/0a5fd5a896eb1df350a21df02a1bb227
es5: https://gist.github.com/flashdesignory/cc29ae5e360fa6011764f0c48a476118
es6-wp: https://gist.github.com/flashdesignory/17436afba2776c97d6f9fe7bc5083769
es6: https://gist.github.com/flashdesignory/5d575c38ee8e8c090aea9d580b17ba2f
react-redux: https://gist.github.com/flashdesignory/16777c04506106351423e33554339636
react: https://gist.github.com/flashdesignory/2c47e3b5b49a968f4d1d1ca27e244c98

**Review by rniwa — APPROVED** [review]
r+

**Pull request merged**
