### PR TITLE
use translations in todomvc tests

### PR DESCRIPTION
**Pull request by flashdesignory**
This is the follow up pr for https://github.com/WebKit/Speedometer/pull/259.

added helper function to assign translations.
todomvc - es5 uses Japanese
todomvc - es6 uses Russian

Happy to swap workloads for the translations, but these seemed reasonable choices.

@kara

### CODE REVIEW

**Comment by flashdesignory** [comment]
chrome before:
chrome_before
chrome after:
chrome_after

safari before:
safari_before
safari after:
safari_after

firefox before:
firefox_before

firefox after:
chrome_after

**Comment by flashdesignory** [comment]
> FTR I don't see the improvement on Javascript-ES6 in Firefox on my machine (which is what I expect).

hmm maybe my machine had a moment of "ok let's optimize firefox only for this one"... will re-run the test and supply updated screenshot

**Comment by flashdesignory** [comment]
updated firefox after screenshot:
Screenshot 2023-07-11 at 9 58 02 AM

**Comment by flashdesignory** [comment]
@rniwa - do you have any feedback or is this good to merge?

**Review by rniwa — APPROVED** [review]

**Pull request merged**
