### PR TITLE
News Site Next

### PR DESCRIPTION
**Pull request by flashdesignory**
This fixes  next.js issue: https://github.com/WebKit/Speedometer/issues/422
A separate pr for Nuxt will do the same. 

The fix here is to add unique ids to any article content that is a list.
This is done in the actual data files, so no need for the app to generate them at any point.

@kara

### CODE REVIEW

**Review by camillobruni — APPROVED** [review]
Generally LGTM: might be worth adding a little test to check for consistency across languages and uniqueness of IDs within a language.

**Comment by flashdesignory** [comment]
yes, absolutely!
Tests are needed and will come in a future PR at some point.

**Review by julienw — APPROVED** [review]
This looks good to me, thanks for the fix.
One more thing: in `section.jsx` you can use `article.id` instead of concatenating the section id with `index`.

**Comment by rniwa** [comment]
Do we have before/after numbers?

**Comment by flashdesignory** [comment]
> Do we have before/after numbers?

here's a snapshot
| browser | before  | after  |
|---|---|---|
| chrome | 72.27 | 70.27 |
| firefox | 77.47 | 72.43 |
| safari | 54.03 | 57.47 |

**Comment by rniwa** [comment]
Is that runtime or pts?

**Comment by flashdesignory** [comment]
> Is that runtime or pts?

we're displaying runtime in the detail screen, right?

**Comment by flashdesignory** [comment]
@rniwa - any concerns to merge this?

**Comment by flashdesignory** [comment]
closing in favor of: https://github.com/WebKit/Speedometer/pull/447

**Pull request closed without merging**
