### PR TITLE
npm run format

### PR DESCRIPTION
**Pull request by camillobruni**
Format all code.

### CODE REVIEW

**Comment by julienw** [comment]
Maybe `assets` in `editors` could be excluded from formatting, this doesn't look worth formatting them.

**Review by rniwa — APPROVED** [review]

**Review by rniwa — APPROVED** [review]

**Review by bgrins — APPROVED** [review]
Feel free to land after excluding the two files discussed above (thanks!)

**Review by flashdesignory — APPROVED** [review]

**Comment by camillobruni** [comment]
Updated  .eslintrc and .prettierrc to exclude `/resources/tentative/editors/assets` and re-formatted again.

**Comment by julienw** [comment]
> Updated .eslintrc and .prettierrc to exclude `/resources/tentative/editors/assets` and re-formatted again.

Thanks, this looks good to me now.

Do you think you could check the format on CI afterwards?

**Comment by camillobruni** [comment]
Yeah I think we should start adding it to the bot.

**Pull request merged**
