### PR TITLE
Add Sanitizing script to react-redux and vue to remove non-inclusive words in dist folders

### PR DESCRIPTION
**Pull request by flashdesignory**
This somewhat addresses https://github.com/WebKit/Speedometer/issues/153

Added a script that runs after the build script of react-redux and vue. 
The sanitize script parses the output folder for offensive words and replaces them.

@kara

### CODE REVIEW

**Comment by flashdesignory** [comment]
Please note - I did not touch this file, which includes a bad word:
`resources/tentative/complex-static-html/generator-dist/app.bundle.js`

**Comment by flashdesignory** [comment]
Please note - I did not touch this file, which includes a bad word:
`resources/tentative/complex-static-html/generator-dist/app.bundle.js`

**Comment by lpardosixtosMs** [comment]
> Please note - I did not touch this file, which includes a bad word: `resources/tentative/complex-static-html/generator-dist/app.bundle.js`
> 
> @lpardosixtosMs

Thanks, we can revisit it after all the changes to that file land.

**Review by rniwa — APPROVED** [review]
Thank you!

**Review by julienw — APPROVED** [review]

**Pull request merged**
